2024-12-13 10:10:30,173 ERROR VPMS.Program.OnException [12] - MESSAGE: Unhandled Error >> 
 System.ArgumentException: Extension 'xls' is not supported. Supported extensions are '.xlsx', '.xlsm', '.xltx' and '.xltm'.
   at ClosedXML.Excel.XLWorkbook.GetSpreadsheetDocumentType(String filePath)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)
   at VPMSWeb.Controllers.TestManagementController.DownloadTestResultListing(TestResultRequestModel data) in C:\Dev\VPMS\VPMS\Controllers\TestManagementController.cs:line 82
   at lambda_method988(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

----------------------------------------------------------------------------

2024-12-13 11:08:14,423 ERROR VPMS.Program.OnException [12] - MESSAGE: Unhandled Error >> 
 System.IO.IOException: The process cannot access the file 'C:\Dev\VPMS\VPMS\Temp\456.xlsx' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)
   at VPMSWeb.Controllers.TestManagementController.DownloadTestResultListing(TestResultRequestModel data) in C:\Dev\VPMS\VPMS\Controllers\TestManagementController.cs:line 95
   at lambda_method988(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

----------------------------------------------------------------------------

2024-12-13 11:50:15,327 ERROR VPMS.Program.MoveNext [281] - MESSAGE: Controller Error >> 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at VPMSWeb.Controllers.LoginController.Logout(Boolean autoLogout) in C:\Dev\VPMS\VPMS\Controllers\LoginController.cs:line 281

----------------------------------------------------------------------------

2024-12-13 11:50:17,208 ERROR VPMS.Program.MoveNext [281] - MESSAGE: Controller Error >> 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at VPMSWeb.Controllers.LoginController.Logout(Boolean autoLogout) in C:\Dev\VPMS\VPMS\Controllers\LoginController.cs:line 281

----------------------------------------------------------------------------

